# Generated by Django 3.2 on 2022-04-07 05:23

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=17, unique=True, validators=[users.models.phone_number_validator]),
        ),
    ]
